export const inputField = [
  {
    label: "Title",
    name: "title",
    type: "text",
    required: true,
    placeholder: "Learn Javascript",
  },
  {
    label: "Author",
    name: "author",
    type: "text",
    required: true,
    placeholder: "Uncle Bob",
  },

  {
    label: "ISBN",
    name: "isbn",
    type: "text",
    required: true,
    placeholder: "9876LKJHHG",
  },
  {
    label: "Genre",
    name: "genre",
    type: "text",
    required: true,
    placeholder: "GENRE",
  },
  {
    label: "Published Year",
    name: "publishedYear",
    type: "number",
    min: "1000",
    required: true,
    placeholder: "2020",
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    as: "textarea",
    maxLength: "5000",
    required: true,
    placeholder: "Book summary ...",
    rows: "5",
  },
];

export const inputFields = [
  {
    label: "Product Name",
    name: "name",
    type: "text",
    required: true,
    placeholder: "Enter product name",
  },

  {
    label: "Price",
    name: "price",
    type: "number",
    required: true,
    placeholder: "Enter price",
    min: 0,
  },
  {
    label: "Sizes",
    name: "sizes",
    type: "select-multiple",
    options: ["S", "M", "L", "XL"],
    required: false,
    placeholder: "Select sizes",
  },
  {
    label: "Image URLs",
    name: "imageLists",
    type: "text",
    as: "textarea",
    required: false,
    placeholder: "Enter image URLs separated by commas",
    rows: 3,
  },
  {
    label: "Stock",
    name: "stock",
    type: "number",
    required: true,
    placeholder: "Enter available stock",
    min: 0,
  },

  {
    label: "Thumbnail URL",
    name: "thumbnail",
    type: "text",
    required: true,
    placeholder: "Enter thumbnail image URL",
  },
  {
    label: "Average Rating",
    name: "averageRating",
    type: "number",
    required: false,
    placeholder: "Leave empty for default (0)",
    step: 0.1,
    min: 0,
    max: 5,
  },
  {
    label: "Review ID",
    name: "reviews",
    type: "text",
    required: true,
    placeholder: "Enter review ObjectId",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    options: ["active", "inactive"],
    required: false,
    placeholder: "Select status",
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    as: "textarea",
    required: true,
    placeholder: "Enter product description",
    rows: 4,
  },
];
