export const userSignUpInputs = [
  {
    label: "First Name",
    controlId: "formGroupFirstName",
    name: "fName",
    required: true,
    Placeholder: "Enter First Name",
    type: "text",
  },
  {
    label: "Last Name",
    controlId: "formGroupLastName",
    name: "lName",
    required: true,
    Placeholder: "Enter Last Name",
    type: "text",
  },
  {
    label: "Email",
    controlId: "formGroupEmail",
    name: "email",
    required: true,
    Placeholder: "Smith@gmail.com",
    type: "email",
  },
  {
    label: "Phone Number",
    controlId: "formGroupPhone",
    name: "phone",
    required: true,
    Placeholder: "0495600003",
    type: "tel",
  },
  {
    label: "Password",
    controlId: "formGroupPassword",
    name: "password",
    required: true,
    Placeholder: "*******",
    type: "password",
  },
  {
    label: "Confirm Password",
    controlId: "formGroupConfirmPassword",
    name: "confirmPassword",
    required: true,
    Placeholder: "*******",
    type: "password",
  },
  {
    label: "thumbnail",
    controlId: "formGroupThumbnail",
    name: "thumbnail",
    required: false,
    Placeholder: "thumbnail",
    type: "text",
    defaultValue: "https://randomuser.me/api/portraits/women/44.jpg",
  },
];
